name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  env:
    REGISTRY: ghcr.io
    GHCR_NAMESPACE: matrix-org/matrix-public-archive
    IMAGE_NAME: matrix-public-archive-test-homeserver

  # Create and publish a Docker image for a Synapse test instance that can
  # federate with each other.
  #
  # Based off of
  # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
  deploy-test-synapse-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images:

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.GHCR_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          context: test/dockerfiles/
          file: 'test/dockerfiles/Synapse.Dockerfile'
          labels: ${{ steps.meta.outputs.labels }}

  tests:
    needs: [deploy-test-synapse-image]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    services:
      hs1:
        image: ${{ env.REGISTRY }}/${{ env.GHCR_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          SERVER_NAME: hs1
      hs2:
        image: ${{ env.REGISTRY }}/${{ env.GHCR_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          SERVER_NAME: hs2

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Install dependencies
      - run: npm ci
      - run: npm run build
      - run: npm test
