name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    needs: [deploy-test-synapse-image]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    services:
      hs1:
        image: ghcr.io/matrix-org/matrix-public-archive/matrix-public-archive-test-homeserver
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          SERVER_NAME: hs1
      hs2:
        image: ghcr.io/matrix-org/matrix-public-archive/matrix-public-archive-test-homeserver
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          SERVER_NAME: hs2

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Install dependencies
      - run: npm ci
      - run: npm run build
      - run: npm test
